version: '3.8'

services:
  app:
    image: doohfy/dooh:beta
    command: |
      ./entrypoint.sh
    environment:
      - DOOHDBConnection=Server=sqlserver,1433;TrustServerCertificate=True;User ID=sa;Password=${SA_PASSWORD};;Initial Catalog=DOOHDB
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - HTTPS_PORTS=443
      - HTTP_PORTS=80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${DOMAIN}.pfx
    volumes:
      - origin-cert:/https/
    depends_on:
      - sqlserver
    deploy:
      restart_policy:
        condition: unless-stopped
        
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${SQL_PORT}:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 1
    volumes:
      - sqlserver-data:/var/opt/mssql
    deploy:
      resources:
          limits:
            cpus: '1'
            memory: 4G
      restart_policy:
        condition: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - app
    deploy:
      mode: replicated
      replicas: ${TUNNEL_REPLICAS}
      restart_policy:
        condition: unless-stopped


volumes:
  sqlserver-data:
  origin-cert:
