name: Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t doohfy/dooh:beta .

      - name: Push Docker image to Docker Hub
        run: docker push doohfy/dooh:beta

      # - name: Notify DevStroop
      #   run: curl -X POST -H "Content-Type: application/json" -d '{"stackId":"06495395-8458-44d8-9a55-6e97508714f3"}' https://node1.devstroop.in/api/stacks/webhooks/06495395-8458-44d8-9a55-6e97508714f3